### ISSUE TITLE
new Number use can be simplified

### ISSUE THREAD

**Issue by jdalton** [d3x0r/JSON6#6]
I noticed json-6 uses `new Number` in places creating number objects then immediately coerces it to a number primitive. Instead you can use just `Number(...)` without the `new` or `+value`.

**Comment by d3x0r** [comment]
Yes; `Number()` over `new Number()` is an (10x) optimization... but it's not `+ value` it's `* value` to recover the sign which ends up outside the number because of keyword `-Infinity`.

`Number( val.string ) * (val.negative?-1:1)`  is slightly faster than `val.negative?-Number( val.string ):Number(val.string);` (2757ms:3811ms)

`(val.negative?-1:1) * Number(val.string);` is slower (3308ms) 

github  tests/testNumberConvert.js

published 0.1.121

**Comment by jdalton** [comment]
Ah cool. `+value` is just a lighter weight form of `Number()` for your use you might need to wrap it in the appropriate parens. See `Number()` performs the internal [ToNumber](https://tc39.github.io/ecma262/#sec-number-constructor-number-value) operation as well as `+` ([Unary Plus](https://tc39.github.io/ecma262/#sec-unary-plus-operator-runtime-semantics-evaluation))

**Comment by d3x0r** [comment]
(+val.number) is 50% slower....
```
(+val.number)
took: 5040
took: 5238
took: 4272
took: 4753
took: 4479
took: 4616

// Number( val.number)
took: 3820
took: 3589
took: 2780
took: 3322
took: 3146
took: 3056
```

**Comment by jdalton** [comment]
\cc @bmeurer

**Comment by bmeurer** [comment]
Traditionally `+x` was desugared to `1*x` (which no longer works with BigInts though), so that's why depending on what you do exactly, `+x` can be a bit slower than just invoking the `Number` constructor.

**Comment by jdalton** [comment]
Thank you @bmeurer!
